export default {
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
    PRODUCT_LOAD_START: "PRODUCT_LOAD_START",
    PRODUCT_LOAD_SUCCESS: "PRODUCT_LOAD_SUCCESS",
    PRODUCT_LOAD_ERROR: "PRODUCT_LOAD_ERROR",
    PRODUCT_SEARCH_START: "PRODUCT_SEARCH_START",
    PRODUCT_SEARCH_SUCCESS: "PRODUCT_SEARCH_SUCCESS",
    PRODUCT_SEARCH_ERROR: "PRODUCT_SEARCH_ERROR"
}