export default {
    //Add product types
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR: "ADD_PRODUCT_ERROR",
    //Load product types
    PRODUCT_LOAD_START: "PRODUCT_LOAD_START",
    PRODUCT_LOAD_SUCCESS: "PRODUCT_LOAD_SUCCESS",
    PRODUCT_LOAD_ERROR: "PRODUCT_LOAD_ERROR",
    //Search product types
    PRODUCT_SEARCH_START: "PRODUCT_SEARCH_START",
    PRODUCT_SEARCH_SUCCESS: "PRODUCT_SEARCH_SUCCESS",
    PRODUCT_SEARCH_ERROR: "PRODUCT_SEARCH_ERROR",
    //Edit product types
    PRODUCT_EDIT_START: "PRODUCT_EDIT_START",
    PRODUCT_EDIT_START_NEXT: "PRODUCT_EDIT_START_NEXT",
    PRODUCT_EDIT_SUCCESS: "PRODUCT_EDIT_SUCCESS",
    PRODUCT_EDIT_ERROR: "PRODUCT_EDIT_ERROR",
    //Delete product types
    PRODUCT_DELETE_START: "PRODUCT_DELETE_START",
    PRODUCT_DELETE_START_NEXT: "PRODUCT_DELETE_START_NEXT",
    PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_ERROR: "PRODUCT_DELETE_ERROR"
}